services:
  apisec:
    build:
      dockerfile: Dockerfile
    image: wwt92829/csc842-apisec
    ports:
      - "8443:443"   # HTTPS
      - "2222:22"    # SSH
    container_name: csc842-apisec
    restart: always