services:
  apisec:
    build:
      dockerfile: Dockerfile
    image: wwt92829/csc842-cycle8
    ports:
      - "8080:80"   # Web server
      - "2222:22"   # SSH
    container_name: csc842-cycle8
    restart: always
